name: jCollector
main: com.staylords.jcollector.JCollector
version: 1.0
author: staylords
website: http://git.staylords.com/

load: POSTWORLD
database: true

depend:
  - Vault
  - Factions
softdepend:
  - ShopGuiPlus
  - WildStacker